### ISSUE TITLE
Plugin crush on Paper server

### ISSUE THREAD

**Issue by uprial** [StarchierOrb/GlobalGamerules#5]
Doesn't work for paper-1.21.1. Could you please fix it?

```
[15:33:08 ERROR]: Error occurred while enabling GlobalGamerules v1.0.0 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at GlobalGamerules-1.0.0.jar/me.starchier.globalgamerules.util.PluginUtil.getVersion(PluginUtil.java:22) ~[GlobalGamerules-1.0.0.jar:?]
at GlobalGamerules-1.0.0.jar/me.starchier.globalgamerules.Globalgamerules.startupInit(Globalgamerules.java:67) ~[GlobalGamerules-1.0.0.jar:?]
at GlobalGamerules-1.0.0.jar/me.starchier.globalgamerules.Globalgamerules.onEnable(Globalgamerules.java:22) ~[GlobalGamerules-1.0.0.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-7-a5d7426]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-7-a5d7426]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-7-a5d7426]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-7-a5d7426]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-7-a5d7426]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-7-a5d7426]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-7-a5d7426]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-7-a5d7426]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-7-a5d7426]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Looks like this line: https://github.com/StarchierOrb/GlobalGamerules/blob/master/src/main/java/me/starchier/globalgamerules/util/PluginUtil.java#L22
expects something like "org.bukkit.craftbukkit,v1_21_R2", but gets only "org.bukkit.craftbukkit"

**Comment by GGNado** [comment]
Replace getVersion() method with this:

```
public String getVersion() {
    String[] splitPackage = plugin.getServer().getClass().getPackage().getName().replace(".", ",").split(",");
    if (splitPackage.length > 3) {
        return splitPackage[3];
    }
    return "Unknown";
}
```
